// <auto-generated />
using System;
using JegyzetekWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JegyzetekWebApp.Migrations
{
    [DbContext(typeof(TodolistDbContext))]
    partial class TodolistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JegyzetekWebApp.Models.Kartya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kartyak");
                });

            modelBuilder.Entity("JegyzetekWebApp.Models.Teendo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KartyaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Kesz")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Letrehozve")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modositva")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tartalom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KartyaId");

                    b.ToTable("Teendok");
                });

            modelBuilder.Entity("JegyzetekWebApp.Models.Teendo", b =>
                {
                    b.HasOne("JegyzetekWebApp.Models.Kartya", "Kartya")
                        .WithMany("Teendok")
                        .HasForeignKey("KartyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kartya");
                });

            modelBuilder.Entity("JegyzetekWebApp.Models.Kartya", b =>
                {
                    b.Navigation("Teendok");
                });
#pragma warning restore 612, 618
        }
    }
}
